apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml

# Add sync wave annotation to ensure operator installs before DataScienceCluster
commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"

# Parameterize the subscription channel
# Edit this value to change the RHOAI subscription channel
patches:
  - target:
      kind: Subscription
      name: rhods-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: fast-3.x
