apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nfd-operator
  - kueue-operator
  - nvidia-dcgm-operator

# Add sync wave annotation to ensure dependencies install first
commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
