apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: {{ .Values.clusterName }}-gpu-{{ .Values.availabilityZone }}
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: {{ .Values.clusterName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ .Values.clusterName }}
      machine.openshift.io/cluster-api-machineset: {{ .Values.clusterName }}-gpu-{{ .Values.availabilityZone }}
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ .Values.clusterName }}
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: {{ .Values.clusterName }}-gpu-{{ .Values.availabilityZone }}
        node-role.kubernetes.io/gpu: ""
    spec:
      metadata:
        labels:
          {{- range $key, $value := .Values.labels }}
          {{ $key }}: {{ $value | quote }}
          {{- end }}
      taints:
        {{- toYaml .Values.taints | nindent 8 }}
      providerSpec:
        value:
          kind: AWSMachineProviderConfig
          apiVersion: machine.openshift.io/v1beta1
          instanceType: {{ .Values.instanceType }}
          ami:
            id: {{ .Values.amiId | quote }}
          blockDevices:
            - ebs:
                volumeSize: {{ .Values.rootVolume.size }}
                volumeType: {{ .Values.rootVolume.type }}
                iops: {{ .Values.rootVolume.iops }}
              deviceName: /dev/sda1
          placement:
            availabilityZone: {{ .Values.availabilityZone }}
            region: {{ .Values.region }}
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - "{{ .Values.infraID }}-node"
            - filters:
                - name: tag:Name
                  values:
                    - "{{ .Values.infraID }}-lb"
          subnet:
            filters:
              - name: tag:Name
                values:
                  - "{{ .Values.infraID }}-subnet-private-{{ .Values.availabilityZone }}"
          iamInstanceProfile:
            id: "{{ .Values.infraID }}-worker-profile"
          tags:
            - name: kubernetes.io/cluster/{{ .Values.infraID }}
              value: owned
            - name: gpu-node
              value: "true"
          userDataSecret:
            name: worker-user-data
