apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../g6-2xlarge

patches:
  - target:
      kind: MachineSet
    patch: |-
      - op: replace
        path: /spec/template/spec/providerSpec/value/instanceType
        value: g6.4xlarge
