apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anythingllm-scc-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anythingllm-scc
subjects:
  - kind: ServiceAccount
    name: anythingllm
    namespace: {{ .Values.namespace }}
