apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: anythingllm

resources:
  - route.yaml

# This kustomization is meant to be applied on top of Helm output
# Use: helm template ... | kubectl apply -f - && kubectl apply -k openshift/
