# AWS g6.4xlarge GPU Configuration
# 1x NVIDIA L4 (24GB GDDR6)
# 16 vCPUs, 64 GB RAM
# Cost: ~$1.62/hour (on-demand, us-east-1)

instanceType: g6.4xlarge
replicas: 1

rootVolume:
  size: 120
  type: gp3
  iops: 3000
