# AWS g6.2xlarge GPU Configuration
# 1x NVIDIA L4 (24GB GDDR6)
# 8 vCPUs, 32 GB RAM
# Cost: ~$1.10/hour (on-demand, us-east-1)

instanceType: g6.2xlarge
replicas: 1

rootVolume:
  size: 120
  type: gp3
  iops: 3000
