apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dependencies  # NFD, Kueue, and optional NVIDIA operators
  - base          # RHOAI operator subscription
  - instance      # DataScienceCluster
